# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Site settings
title: "Robert Mezian"
description: >- # this means to ignore newlines until "baseurl:"
include:
  - assets/custom.css
github_username:  ramezian1
linkedin_username: robert-mezian
